n = int(input('digite um valor: '))
print(n)
n1 = float(input('digite outro valor: '))
print(n1)
n2 = bool(input('digite um valor: '))
n3 = bool(input('não digite um valor: '))
print(n2, n3)
n4 = str(input('escreva algo: '))
print(n4)
